import React, { useEffect, useState } from 'react';
import { ArrowRight, Droplets, MapPinned, ShieldCheck, Sprout, Waves } from 'lucide-react';
import '../../styles/feedback.css';

const audiences = [['Watershed & Government Teams', 'Plan interventions across springs and watersheds.'], ['Hydrogeologists & Researchers', 'Explore recharge patterns and validate potential zones.'], ['Field Teams & Communities', 'Bring observations from the ground back into the planning process.']];

function MapGraphic() { return <div className="map-graphic"><div className="map-bar"><span className="map-brand">DHAARA / LIVE MAP</span><span>Kandhamal micro-catchment</span><i>●</i></div><svg viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"><defs><pattern id="grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="currentColor" strokeWidth="1" /></pattern></defs><rect width="1000" height="520" fill="url(#grid)" className="map-grid" /><path d="M-40 85 C150 25 240 165 380 105 S630 30 760 125 S950 195 1060 55 M-30 165 C125 110 225 245 370 182 S650 105 790 204 S950 265 1060 135 M-30 258 C145 185 240 330 412 275 S640 198 810 292 S940 350 1060 236 M-30 360 C120 285 270 430 430 355 S660 285 800 398 S930 455 1050 335" className="contour" /><path d="M215 25 L455 472 M603 28 L750 498" className="fracture" /><path d="M220 168 Q290 106 370 175 T337 302 Q275 343 210 260 Z" className="recharge-a" /><path d="M567 295 Q655 204 760 301 T686 445 Q595 422 567 295 Z" className="recharge-b" /><path d="M40 435 C245 373 365 500 560 405 S824 343 1000 438" className="watercourse" /></svg><div className="map-pin pin-one"><span /><b>Dev-Dhara #01</b></div><div className="map-pin pin-two"><span /><b>Recharge zone</b></div><div className="map-key"><span><i className="dot" /> Spring</span><span><i className="line" /> Fracture</span><span><i className="area" /> Recharge</span></div></div>; }

export function LandingPage({ onOpenDemo, onGetStarted }) {
  const [feedbackOpen, setFeedbackOpen] = useState(false);
  useEffect(() => { const items = document.querySelectorAll('[data-reveal]'); const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) entry.target.classList.add('is-visible'); }), { threshold: 0.15 }); items.forEach((item) => observer.observe(item)); return () => observer.disconnect(); }, []);
  const goToSection = (event, id) => { event.preventDefault(); document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const openApp = (path) => { window.location.assign(path); };
  const submitFeedback = (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const subject = encodeURIComponent(`DHAARA feedback — ${form.get('topic') || 'General'}`); const body = encodeURIComponent(`Name: ${form.get('name') || 'Not provided'}\nEmail: ${form.get('email') || 'Not provided'}\n\nFeedback:\n${form.get('message')}`); window.location.href = `mailto:saniaanees91@gmail.com?subject=${subject}&body=${body}`; setFeedbackOpen(false); };
  return <div className="dhaara-site narrative-site">
    <header className="site-nav"><a href="#top" onClick={(event) => goToSection(event, 'top')} className="wordmark"><span>DH</span>AARA</a><nav className="nav-links"><a href="#human-reason" onClick={(event) => goToSection(event, 'human-reason')}>Why springs</a><a href="#how-it-works" onClick={(event) => goToSection(event, 'how-it-works')}>How it works</a><a href="#methodology" onClick={(event) => goToSection(event, 'methodology')}>Methodology</a><a href="#who-its-for" onClick={(event) => goToSection(event, 'who-its-for')}>Who it serves</a></nav><button className="nav-cta" onClick={onOpenDemo}>See it live <ArrowRight size={16} /></button></header>
    <main id="top">
      <section className="photo-panel hero-panel"><div className="hero-copy" data-reveal><p className="eyebrow">Spring intelligence for resilient communities</p><h1>Water begins<br />somewhere.<br /><em>We help you find it.</em></h1><p className="lede">AI-powered geospatial intelligence for <b>spring recharge, revival, and watershed planning</b> in India's vulnerable and tribal regions.</p><div className="hero-actions"><button className="primary-action" onClick={onOpenDemo}>See It Live <ArrowRight size={18} /></button><button className="text-action" onClick={onGetStarted}>Get Started <ArrowRight size={17} /></button></div><p className="support-line">From landscape data to actionable intervention sites.</p></div><div className="hero-collage" aria-label="DHAARA landscapes and water communities"><figure className="collage-panel terrain"><img src="/images/hero-landscape.png" alt="Mountain and forest terrain" /><figcaption>Read the watershed</figcaption></figure><figure className="collage-panel spring"><img src="/images/natural-spring-well.png" alt="A natural springwell" /><figcaption>Start with a spring</figcaption></figure><figure className="collage-panel community"><img src="/images/tribal-community-1.png" alt="A tribal community landscape" /><figcaption>Plan with the people who live there</figcaption></figure><div className="collage-rule" aria-hidden="true"><span /> <span /> <span /></div></div></section>
      <section id="human-reason" className="photo-panel human-panel"><img src="/images/tribal-community-1-sharp.png" alt="A community in a forested valley" /><div className="photo-wash human-wash" /><div className="human-copy" data-reveal><p className="eyebrow">The human reason</p><h2>For communities, a spring is more than <em>a water source.</em></h2><div className="human-lines"><span>It is drinking water.</span><span>It is agriculture.</span><span>It is a daily journey.</span><span>It is part of the landscape they have lived with for generations.</span></div><p>But when springs weaken, knowing <strong>where and how to restore them</strong> is difficult.</p></div></section>
      <section id="problem" className="problem-section"><div className="section-copy" data-reveal><p className="eyebrow">The problem</p><h2>The water is there.<br /><em>The challenge is knowing where to look.</em></h2><p>Spring recharge zones are shaped by terrain, rainfall, drainage, geology, vegetation, and land use. Finding that relationship traditionally requires extensive field investigation.</p><p className="statement">DHAARA brings those signals together.</p></div><div className="signal-graphic" data-reveal><div className="signal-orbit orbit-a" /><div className="signal-orbit orbit-b" /><div className="signal-core"><Waves size={31} /><span>SPRING</span></div><div className="signal-label label-a">terrain</div><div className="signal-label label-b">rainfall</div><div className="signal-label label-c">drainage</div><div className="signal-label label-d">geology</div><div className="signal-label label-e">vegetation</div><div className="signal-label label-f">land use</div></div></section>
      <section id="how-it-works" className="steps-section"><div className="steps-heading" data-reveal><p className="eyebrow">What DHAARA does</p><h2>From terrain to <em>intervention.</em></h2></div><div className="step-grid">{[[MapPinned,'01','MAP','Identify probable spring recharge zones using geospatial and environmental data.'],[Sprout,'02','PRIORITIZE','Find and rank locations where recharge interventions could have the greatest potential.'],[ShieldCheck,'03','PROTECT','Screen proposed sites against landslide susceptibility and other terrain risks.']].map(([Icon, number, label, text]) => <article className="step-card" data-reveal key={number}><div className="step-top"><span>{number}</span><Icon size={23} /></div><h3>{label}</h3><p>{text}</p></article>)}</div></section>
      <section id="product" className="product-section"><div className="product-copy" data-reveal><p className="eyebrow">The product</p><h2>See the landscape <em>differently.</em></h2><h3>One spring.<br />One watershed.<br />A map of possibilities.</h3><p>DHAARA transforms complex geospatial signals into an understandable planning layer for the people responsible for restoring springs.</p><button className="primary-action" onClick={onOpenDemo}>Explore the Live Demo <ArrowRight size={18} /></button></div><div className="product-map" data-reveal><MapGraphic /></div></section>
      <section id="methodology" className="photo-panel explain-section"><img src="/images/tribal-village-hill-sharp.jpg" alt="A hillside landscape" /><div className="photo-wash explain-wash" /><div className="explain-copy" data-reveal><p className="eyebrow">Explainability</p><h2>Every recommendation has <em>a reason.</em></h2><p>When DHAARA identifies a potential intervention site, it shows the factors behind the recommendation.</p><div className="score-card"><div><span>Recharge potential</span><b>HIGH</b></div><div><span>Terrain suitability</span><b>HIGH</b></div><div><span>Runoff potential</span><b>HIGH</b></div><div><span>Landslide susceptibility</span><b className="low">LOW</b></div></div><blockquote><strong>AI assists the decision.</strong><br />The field validates it.</blockquote></div></section>
      <section id="who-its-for" className="audience-section"><div data-reveal><p className="eyebrow">Who it's for</p><h2>Built for the people who <em>restore landscapes.</em></h2></div><div className="audience-list">{audiences.map(([title, text], index) => <article data-reveal key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section id="vision" className="photo-panel vision-section"><img src="/images/hero-landscape-sharp.png" alt="A mountain watershed" /><div className="photo-wash vision-wash" /><div className="vision-copy" data-reveal><p className="eyebrow">The larger vision</p><h2>A living map of <em>India's springs.</em></h2><p>DHAARA is built around a simple idea:</p><blockquote>Better understanding of the landscape can lead to better decisions about the water that sustains it.</blockquote><div className="vision-steps"><span>Start with one spring.</span><i>→</i><span>Understand its watershed.</span><i>→</i><span>Find where restoration can begin.</span></div></div></section>
      <section className="final-cta"><p className="eyebrow">DHAARA</p><h2>Find where the water <em>begins.</em></h2><p>Explore a spring. Map its recharge. Plan its revival.</p><button className="primary-action" onClick={onOpenDemo}>See It Live <ArrowRight size={18} /></button></section>
    </main>
    <footer className="site-footer expanded-footer"><div><a href="#top" className="wordmark"><span>DH</span>AARA</a><p>Spring Intelligence for<br />Resilient Communities.</p></div><div className="footer-links"><div><b>PRODUCT</b><button onClick={() => openApp('/app')}>Live Workspace</button><button onClick={() => openApp('/app/analysis')}>How It Works</button><button onClick={() => openApp('/app/methodology')}>Methodology</button></div><div><b>PLATFORM</b><button onClick={() => openApp('/app/analysis')}>Recharge Mapping</button><button onClick={() => openApp('/app/sites')}>Intervention Planning</button><button onClick={() => openApp('/app/sites')}>Risk Assessment</button></div><div><b>ABOUT</b><a href="#human-reason" onClick={(event) => goToSection(event, 'human-reason')}>Our Approach</a><button onClick={() => setFeedbackOpen(true)}>Contact & feedback</button></div></div><div className="footer-bottom"><span>Built for India's spring-dependent communities. © 2026 DHAARA</span><span>Decision support for field action. Not a substitute for hydrogeological validation.</span></div></footer>
    {feedbackOpen && <div className="feedback-backdrop" role="dialog" aria-modal="true" aria-labelledby="feedback-title"><form className="feedback-form" onSubmit={submitFeedback}><button type="button" className="feedback-close" onClick={() => setFeedbackOpen(false)} aria-label="Close feedback form">×</button><p className="eyebrow">Contact DHAARA</p><h2 id="feedback-title">Send feedback</h2><p>Your message will open in your email app addressed to Sania Anees.</p><label>Your name<input name="name" /></label><label>Email address<input name="email" type="email" /></label><label>Topic<select name="topic"><option>General feedback</option><option>Data correction</option><option>Partnership</option><option>Technical issue</option></select></label><label>Your message<textarea name="message" required placeholder="Tell us what would make DHAARA better." /></label><button className="primary-action" type="submit">Continue to email <ArrowRight size={17} /></button><small>saniaanees91@gmail.com</small></form></div>}
  </div>;
}
