import React, { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, BarChart3, ClipboardCheck, FileText, LogOut, Map, MapPin, Menu, Search, Sprout, X } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { assessmentFor, CANDIDATE_SITES, DEMO_NOTICE, DEMO_SPRINGS } from '../../data/demoAnalysis';
import { runDemoAnalysis } from '../../services/demoAnalysisEngine';
import { fieldObservationRepository } from '../../repositories/fieldObservationRepository';
import { GeoMap } from './GeoMap';
import '../../styles/workspace.css';
import '../../styles/workspace-overrides.css';
import '../../styles/investigation.css';
import '../../styles/investigation-overrides.css';
import '../../styles/workspace-clarity.css';
import '../../styles/workspace-premium.css';

const NAV = [[Map, 'Overview', '/app'], [MapPin, 'Springs', '/app/springs'], [BarChart3, 'Analysis', '/app/analysis'], [Sprout, 'Interventions', '/app/sites'], [ClipboardCheck, 'Fieldwork', '/app/validation'], [FileText, 'Reports', '/app/reports']];
const OVERVIEW_SECTIONS = [['overview-top', 'Overview'], ['assessment', 'Assessment'], ['evidence', 'Evidence'], ['interventions', 'Interventions'], ['risk', 'Risk'], ['fieldwork', 'Fieldwork'], ['report', 'Report']];
const titleFor = (path) => NAV.find(([, , target]) => target === path)?.[1] || 'Overview';

function SpringSearch({ value, onChange, onSelect }) {
  const results = DEMO_SPRINGS.filter((item) => item.name.toLowerCase().includes(value.toLowerCase()) || item.region.toLowerCase().includes(value.toLowerCase()));
  return <div className="spring-search"><label><Search size={15}/><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="Search a spring" /></label>{value && <div className="spring-results">{results.length ? results.map((item) => <button key={item.spring_id} onClick={() => onSelect(item)}><b>{item.name}</b><span>{item.region} · {item.observed_discharge}</span></button>) : <span>No demonstration spring matches.</span>}</div>}</div>;
}

function Workflow({ analysed, showSites }) { return <div className="workflow-rail">{['Spring', 'Evidence', 'Recharge', 'Confidence', 'Sites', 'Risk', 'Validate'].map((step, index) => <span className={(index === 0 || analysed && index < 5 || showSites && index < 6) ? 'done' : ''} key={step}><i>{index + 1}</i>{step}</span>)}</div>; }

function FieldForm({ spring }) {
  const [saved, setSaved] = useState(null); const [form, setForm] = useState({ discharge: '', condition: 'Flowing', notes: '', date: new Date().toISOString().slice(0, 10), photo: '' });
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event) => { event.preventDefault(); setSaved(fieldObservationRepository.save({ springId: spring.spring_id, springName: spring.name, latitude: spring.latitude, longitude: spring.longitude, ...form })); };
  const gps = Number.isFinite(spring.latitude) ? `${spring.latitude.toFixed(4)}, ${spring.longitude.toFixed(4)}` : 'Coordinates unavailable in supplied study record';
  return <section className="page-card validation-form"><div><p className="panel-label">FIELD VALIDATION</p><h2>Prediction → observation → verification</h2><p>Capture a GPS-linked observation for <b>{spring.name}</b>. Records are saved in this browser through the current data repository.</p></div><form onSubmit={submit}><label>Observed discharge (LPM)<input required value={form.discharge} onChange={(e) => update('discharge', e.target.value)} inputMode="decimal" /></label><label>Spring condition<select value={form.condition} onChange={(e) => update('condition', e.target.value)}><option>Flowing</option><option>Weak</option><option>Dry</option><option>Blocked</option></select></label><label>Observation date<input type="date" value={form.date} onChange={(e) => update('date', e.target.value)} /></label><label>Photo reference<input type="file" accept="image/*" onChange={(e) => update('photo', e.target.files?.[0]?.name || '')} /></label><label className="wide">Notes<textarea value={form.notes} onChange={(e) => update('notes', e.target.value)} placeholder="What did you observe on site?" /></label><small>GPS context: {gps}</small><button className="dark-button">Save field observation</button></form>{saved && <div className="saved-note">Saved locally at {new Date(saved.savedAt).toLocaleTimeString()}. A server repository can replace this adapter later without changing the form.</div>}</section>;
}

function InvestigationOverview({ spring, springs, analysis, showSites, site, onAnalyse, onSpring, onSite, onFieldwork, onReport }) {
  const selectById = (id) => { const next = springs.find((item) => item.spring_id === id); if (next) onSpring(next); };
  const assessment = assessmentFor(spring);
  return <div className="investigation"><section id="overview-top" className="investigation-hero"><div><p className="panel-label">SPRING INTELLIGENCE</p><h2>Understand where water begins.</h2><p>Explore inventoried springs, assess recharge potential, identify intervention opportunities and validate findings in the field.</p></div><div className="investigation-actions"><label className="overview-spring-select"><span>Selected spring</span><select value={spring.spring_id} onChange={(event) => onSpring(springs.find((item) => item.spring_id === event.target.value))}>{springs.map((item) => <option key={item.spring_id} value={item.spring_id}>{item.name}</option>)}</select></label><button className="quiet-button" onClick={onFieldwork}>+ Field observation</button></div></section><section className="atlas-section"><GeoMap spring={spring} springs={springs} analysed={Boolean(analysis && analysis !== 'running')} showSites={showSites} onSelectSpring={selectById} onSelectSite={onSite} /><p className="map-caption">Select a mapped spring to inspect its record. Historical intervention records are distinguished from inventoried records.</p></section>
    <section className="content-section summary-section"><p className="panel-label">SPRING INTELLIGENCE</p><h2>An evidence-based view of the selected spring and its surrounding landscape.</h2><div className="fact-row"><span><b>{spring.elevation} m</b>Elevation</span><span><b>{spring.type}</b>Spring type</span><span><b>{spring.region}</b>Location</span><span><b>{spring.observed_discharge}</b>Available discharge</span><span><b>{spring.geology === 'Not specified in technical record' ? 'Partial' : 'Good'}</b>Data coverage</span></div></section>
    <section id="assessment" className="content-section assessment-section"><div><p className="panel-label">RECHARGE ASSESSMENT</p><h2>Suitability, with appropriate uncertainty.</h2><p>Higher suitability areas are associated with the environmental factors included in the assessment. Confidence reflects the completeness and strength of available evidence.</p>{!analysis ? <button className="dark-button" onClick={onAnalyse}>Assess recharge suitability</button> : <span className="assessment-note">Assessment available for the selected spring record.</span>}</div><div className="assessment-results"><span><b>{analysis && analysis !== 'running' ? assessment.suitability : '—'}<small>%</small></b>Recharge suitability</span><span><b>{analysis && analysis !== 'running' ? assessment.confidence : '—'}<small>%</small></b>Confidence</span></div></section>
    <section id="evidence" className="content-section evidence-section"><div><p className="panel-label">WHAT'S INFLUENCING THE ASSESSMENT?</p><h2>Supporting evidence, not black-box scores.</h2></div><div className="evidence-list">{[['Terrain','DEM',assessment.terrain],['Rainfall','Historical climate layer',assessment.rainfall],['Geology',spring.geology, spring.geology.startsWith('Not specified') ? 'Partial' : 'Available'],['Land cover',spring.land,'Available'],['Drainage','Mapped drainage context',assessment.drainage],['Spring observations',spring.discharge2010 ? '2010–2011 intervention record' : 'Technical inventory record', spring.discharge2010 ? 'Available' : 'Limited']].map(([name, source, status]) => <div key={name}><b>{name}</b><span>{source}</span><i className={status.toLowerCase()}>{status}</i></div>)}</div></section>
    <section className="content-section zone-section"><div><p className="panel-label">EXPLORE THE RECHARGE ZONE</p><h2>Read the spring in its terrain context.</h2><p>Use the map layers to inspect spring inventory, drainage, recharge suitability and risk screening without losing the geographic context.</p></div><button className="quiet-button" onClick={() => document.querySelector('.map-tools button')?.click()}>Explore layers</button></section>
    <section id="interventions" className="content-section interventions-section"><div><p className="panel-label">WHERE SHOULD WE INVESTIGATE?</p><h2>Potential intervention sites</h2><p>DHAARA ranks potential locations within suitable areas while screening for identified environmental risks. These are not guaranteed construction sites.</p></div><div className="candidate-grid">{[['SITE A','87','79','Low'],['SITE B','81','72','High'],['SITE C','76','68','Moderate']].map(([id, score, confidence, risk], index) => <button key={id} onClick={() => onSite(id)}><span>0{index + 1}</span><b>{id}</b><small>{score}% suitability · {confidence}% confidence</small><i className={`risk ${risk.toLowerCase()}`}>{risk} risk</i></button>)}</div></section>
    <section id="risk" className="content-section risk-section"><div><p className="panel-label">RISK SCREENING</p><h2>What still needs closer investigation?</h2></div><div><span>Landslide susceptibility <b>{assessment.risk}</b></span><span>Slope <b>High</b></span><span>Drainage relationship <b>{assessment.drainage}</b></span><span>Accessibility <b>Moderate</b></span><span>Data availability <b>{assessment.confidence >= 70 ? 'Good' : 'Partial'}</b></span><p>Requires further field assessment before any intervention decision.</p></div></section>
    <section id="fieldwork" className="content-section field-section"><div><p className="panel-label">TAKE THE MODEL TO THE FIELD</p><h2>Predict → investigate → verify → record.</h2><p>Record GPS location, photograph, observed discharge, spring condition, drainage, land condition and notes alongside the original model result.</p></div><button className="dark-button" onClick={onFieldwork}>Add field observation</button></section>
    <section className="learning-strip"><span><b>PREDICT</b>Recharge assessment</span><i>↓</i><span><b>VERIFY</b>Field observation</span><i>↓</i><span><b>LEARN</b>Updated evidence</span></section><section className="content-section data-section"><div><p className="panel-label">DATA & EVIDENCE</p><h2>Transparent source records.</h2></div><button className="quiet-button" onClick={() => window.location.assign('/app/data')}>View data sources</button></section><section id="report" className="report-section"><div><p className="panel-label">SPRING ASSESSMENT REPORT</p><h2>Compile this investigation.</h2><p>Spring profile, environmental evidence, recharge assessment, intervention candidates and field observations.</p></div><button className="dark-button" onClick={onReport}>Generate report</button></section></div>;
}

export function DhaaraWorkspace({ user, onLogout, onBack }) {
  const navigate = useNavigate(); const location = useLocation(); const route = location.pathname.replace(/\/$/, '') || '/app'; const pageTitle = titleFor(route);
  const [drawer, setDrawer] = useState(false); const [accountOpen, setAccountOpen] = useState(false); const [activeSection, setActiveSection] = useState('overview-top'); const [spring, setSpring] = useState(DEMO_SPRINGS[0]); const [search, setSearch] = useState(''); const [analysis, setAnalysis] = useState(null); const [stage, setStage] = useState(null); const [showSites, setShowSites] = useState(false); const [siteId, setSiteId] = useState('SITE A'); const [whyOpen, setWhyOpen] = useState(false);
  const site = useMemo(() => CANDIDATE_SITES.find((item) => item.id === siteId) || CANDIDATE_SITES[0], [siteId]);
  const selectSpring = (next) => { setSpring(next); setSearch(''); setAnalysis(null); setShowSites(false); setSiteId('SITE A'); setWhyOpen(false); navigate('/app'); };
  const analyse = async (destination = '/app/analysis') => { setAnalysis('running'); setShowSites(false); const result = await runDemoAnalysis(spring, setStage); setAnalysis(result); setStage(null); navigate(destination); if (destination === '/app') setTimeout(() => document.getElementById('assessment')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); };
  useEffect(() => { if (route !== '/app') return undefined; const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) setActiveSection(entry.target.id); }), { rootMargin: '-30% 0px -55% 0px' }); OVERVIEW_SECTIONS.forEach(([id]) => document.getElementById(id) && observer.observe(document.getElementById(id))); return () => observer.disconnect(); }, [route]);
  const contextualPanel = <div className="map-dock"><p className="panel-label">SELECT A STUDY SPRING</p><label className="spring-select"><span>Spring record</span><select value={spring.spring_id} onChange={(event) => selectSpring(DEMO_SPRINGS.find((item) => item.spring_id === event.target.value))}>{DEMO_SPRINGS.map((item) => <option value={item.spring_id} key={item.spring_id}>{item.name} — {item.spring_id}</option>)}</select></label><h2>{spring.name}</h2><span>{spring.region} · {spring.type}</span><div className="dock-metrics"><b>{spring.observed_discharge}<small>Lean-period discharge ({spring.observation_date})</small></b><b>{spring.elevation} m<small>Elevation</small></b></div>{!analysis && <button className="dark-button" onClick={analyse}>Analyse spring →</button>}{analysis === 'running' && <div className="analysis-running"><b>{stage?.label || 'Preparing analysis'}</b><span>Local study-data analysis in progress</span></div>}</div>;
  const mapView = <><div className="map-column"><GeoMap spring={spring} springs={DEMO_SPRINGS} analysed={Boolean(analysis && analysis !== 'running')} showSites={showSites} onSelectSpring={(id) => selectSpring(DEMO_SPRINGS.find((item) => item.spring_id === id))} onSelectSite={(id) => { setSiteId(id); setWhyOpen(true); }} /><Workflow analysed={Boolean(analysis && analysis !== 'running')} showSites={showSites} /></div>{contextualPanel}</>;
  return <div className="workspace"><aside className={drawer ? 'workspace-nav open' : 'workspace-nav'}><div className="workspace-brand">DH<span>AARA</span><small>Find where the water begins.</small><div className="sidebar-signal"><i /><i /><i /><span>9 study springs</span></div></div><nav>{NAV.map(([Icon, label, target]) => <button className={route === target ? 'selected' : ''} key={label} onClick={() => { navigate(target); setDrawer(false); }}><Icon size={18}/>{label}<em>→</em></button>)}</nav>{route === '/app' && <div className="section-spy"><p>INVESTIGATION</p>{OVERVIEW_SECTIONS.map(([id, label]) => <button key={id} className={activeSection === id ? 'active' : ''} onClick={() => document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>{label}</button>)}</div>}<div className="nav-bottom"><button onClick={onBack}>← Public site</button></div></aside><main className="workspace-main"><header className="workspace-header"><button className="mobile-menu" onClick={() => setDrawer(true)}><Menu size={23}/></button><button className="header-back" onClick={() => route === '/app' ? onBack() : navigate(-1)} aria-label="Go back" title="Go back"><ArrowLeft size={22}/></button><div><p>SPRING INTELLIGENCE PLATFORM</p><h1>{pageTitle}</h1></div><div className="header-actions">{user && <div className="account-menu"><button className="user-avatar" onClick={() => setAccountOpen((value) => !value)} aria-expanded={accountOpen} aria-label="Open account menu">{user.displayName?.[0] || 'D'}</button>{accountOpen && <div className="account-popover"><b>{user.displayName || 'DHAARA user'}</b><span>{user.email}</span><button onClick={onLogout}><LogOut size={14} /> Sign out</button></div>}</div>}</div></header><div className="demo-notice"><span>STUDY DATA</span>{DEMO_NOTICE}</div>
    {route === '/app' && <InvestigationOverview spring={spring} springs={DEMO_SPRINGS} analysis={analysis} showSites={showSites} site={site} onSpring={selectSpring} onAnalyse={() => analyse('/app')} onSite={(id) => { setSiteId(id); setShowSites(true); document.querySelector('.atlas-map')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); }} onFieldwork={() => navigate('/app/validation')} onReport={() => window.print()} />}
    {route === '/app/springs' && <section className="page-card"><p className="panel-label">NINE SUPPLIED STUDY RECORDS</p><h2>Choose a spring context</h2><div className="spring-list">{DEMO_SPRINGS.map((item) => <button key={item.spring_id} className={item.spring_id === spring.spring_id ? 'chosen' : ''} onClick={() => selectSpring(item)}><b>{item.name} · {item.spring_id}</b><span>{item.region}</span><small>{item.type} · {item.observed_discharge} · {item.source}</small></button>)}</div></section>}
    {route === '/app/analysis' && <section className="map-workspace">{mapView}<div className="analysis-card">{analysis && analysis !== 'running' ? <><p className="panel-label">ANALYSIS RESULT · DEMONSTRATION</p><h2>Recharge suitability <strong>{analysis.rechargeScore}<small>/100</small></strong></h2><b className="score-tag">{analysis.confidenceScore}% · {analysis.confidence} confidence</b><p>Weighted multi-factor demonstration output, not a calibrated probability.</p><div className="evidence-grid">{analysis.evidence.map(([name, status]) => <span key={name}>{name}<b className={status.toLowerCase()}>{status}</b></span>)}</div><button className="dark-button" onClick={() => { setShowSites(true); navigate('/app/sites'); }}>Find potential sites →</button></> : <><h2>Ready to analyse this spring</h2><p>Run the local, evidence-led demonstration workflow to reveal derived layers and candidate screening.</p><button className="dark-button" onClick={analyse}>Start analysis →</button></>}</div></section>}
    {route === '/app/sites' && <section className="map-workspace">{mapView}<div className="sites-card"><p className="panel-label">CANDIDATE INTERVENTION SITES</p>{analysis && analysis !== 'running' ? <>{!showSites ? <button className="dark-button" onClick={() => setShowSites(true)}>Find potential sites</button> : <div className="site-list">{CANDIDATE_SITES.map((item) => <button key={item.id} className={site.id === item.id ? 'chosen' : ''} onClick={() => { setSiteId(item.id); setWhyOpen(true); }}><span><b>{item.id} · {item.name}</b><small>{item.intervention}</small></span><span><b>{item.score}/100</b><small className={`risk ${item.risk.toLowerCase()}`}>{item.risk} risk</small></span></button>)}</div>}</> : <><p>Analyse the selected spring before generating candidate sites.</p><button className="dark-button" onClick={analyse}>Analyse spring →</button></>}</div>{whyOpen && <aside className="why-drawer"><button aria-label="Close explanation" onClick={() => setWhyOpen(false)}>×</button><p className="panel-label">WHY THIS RESULT</p><h2>{site.id} · {site.name}</h2><strong>{site.score}/100 suitability</strong><span className={`risk ${site.risk.toLowerCase()}`}>Risk screening: {site.risk}</span><h3>{site.intervention}</h3><ul>{site.why.map((reason) => <li key={reason}>{reason}</li>)}</ul><small>Decision support only. Field and engineering validation are required before implementation.</small></aside>}</section>}
    {route === '/app/validation' && <FieldForm spring={spring} />}
    {route === '/app/reports' && <section className="page-card"><p className="panel-label">SPRING ASSESSMENT REPORT</p><h2>Compile this investigation.</h2><p>Generate a print-ready report containing the selected spring profile, environmental evidence, recharge assessment, intervention candidates and field observations.</p><button className="dark-button" onClick={() => window.print()}>Generate report</button></section>}
    {route === '/app/data' && <section className="page-card"><p className="panel-label">DATA LAYERS</p><h2>Source-aware analysis inputs</h2><div className="data-table"><span><b>Spring record</b><i>Demonstration data</i><small>Visible on map before analysis</small></span><span><b>Recharge suitability</b><i>Derived demonstration layer</i><small>Revealed after analysis; not field-validated</small></span><span><b>Candidate sites</b><i>Derived demonstration candidate</i><small>Revealed only after explicit site search</small></span><span><b>Geology</b><i>Unavailable in demo</i><small>Not substituted with invented values</small></span></div><p>Provenance and future live-source references are recorded in <code>data/sources.md</code>.</p></section>}
    {route === '/app/methodology' && <section className="page-card method-card"><p className="panel-label">METHODOLOGY</p><h2>Evidence first. Intervention second.</h2>{['Select a spring record and geographic context.', 'Review available terrain, rainfall, land-cover and field evidence.', 'Derive a clearly-labelled demonstration recharge layer.', 'Screen potential sites against terrain risk.', 'Validate any recommendation in the field before implementation.'].map((item, index) => <span key={item}><b>0{index + 1}</b>{item}</span>)}</section>}
  </main></div>;
}
