import React, { useEffect, useState } from 'react';
import { ArrowLeft, BarChart3, ClipboardCheck, FileText, LogOut, Map, MapPin, Menu, Sprout } from 'lucide-react';
import { DEMO_NOTICE, DEMO_SPRINGS, displayValue, hasPairedDischarge } from '../../data/demoAnalysis';
import { GeoMap } from './GeoMap';
import '../../styles/workspace.css';
import '../../styles/workspace-overrides.css';
import '../../styles/investigation.css';
import '../../styles/investigation-overrides.css';
import '../../styles/workspace-clarity.css';
import '../../styles/workspace-premium.css';

const NAV = [[Map, 'Overview', 'overview'], [MapPin, 'Springs', 'springs'], [BarChart3, 'Analysis', 'analysis'], [Sprout, 'Interventions', 'interventions'], [ClipboardCheck, 'Fieldwork', 'fieldwork'], [FileText, 'Reports', 'reports']];
const text = (value) => value || 'Not established in supplied source';

export function DhaaraWorkspace({ user, onLogout, onBack }) {
  const [spring, setSpring] = useState(DEMO_SPRINGS[0]); const [active, setActive] = useState('overview'); const [drawer, setDrawer] = useState(false); const [accountOpen, setAccountOpen] = useState(false);
  useEffect(() => { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActive(entry.target.id)), { rootMargin: '-28% 0px -58% 0px' }); NAV.forEach(([, , id]) => { const item = document.getElementById(id); if (item) observer.observe(item); }); return () => observer.disconnect(); }, []);
  const scrollTo = (id) => { document.getElementById(id)?.scrollIntoView({ behavior: 'smooth', block: 'start' }); setDrawer(false); };
  const paired = hasPairedDischarge(spring);
  return <div className="workspace"><aside className={drawer ? 'workspace-nav open' : 'workspace-nav'}><div className="workspace-brand">DH<span>AARA</span><small>Find where the water begins.</small><div className="sidebar-signal"><i /><i /><i /><span>9 study springs</span></div></div><nav>{NAV.map(([Icon, label, id]) => <button key={id} className={active === id ? 'selected' : ''} onClick={() => scrollTo(id)}><Icon size={19}/>{label}<em>→</em></button>)}</nav><div className="nav-bottom"><button onClick={onBack}>← Public site</button></div></aside><main className="workspace-main"><header className="workspace-header"><button className="mobile-menu" onClick={() => setDrawer(true)}><Menu size={23}/></button><button className="header-back" onClick={onBack} aria-label="Back to public site"><ArrowLeft size={22}/></button><div><p>SPRING INTELLIGENCE PLATFORM</p><h1>DHAARA</h1></div><div className="header-actions">{user && <div className="account-menu"><button className="user-avatar" onClick={() => setAccountOpen(!accountOpen)}>{user.displayName?.[0] || 'D'}</button>{accountOpen && <div className="account-popover"><b>{user.displayName || 'DHAARA user'}</b><span>{user.email}</span><button onClick={onLogout}><LogOut size={14} /> Sign out</button></div>}</div>}</div></header><div className="demo-notice"><span>STUDY DATA</span>{DEMO_NOTICE}</div><div className="investigation">
    <section id="overview" className="investigation-hero"><div><p className="panel-label">SPRING INTELLIGENCE</p><h2>Read the documented record.</h2><p>Select one of the nine supplied springs. DHAARA preserves missing values rather than turning them into prediction scores.</p></div><label className="overview-spring-select"><span>Selected spring</span><select value={spring.spring_id} onChange={(e) => setSpring(DEMO_SPRINGS.find((item) => item.spring_id === e.target.value))}>{DEMO_SPRINGS.map((item) => <option value={item.spring_id} key={item.spring_id}>{item.name}</option>)}</select></label></section>
    <section id="springs" className="atlas-section"><GeoMap spring={spring} springs={DEMO_SPRINGS} onSelectSpring={(id) => setSpring(DEMO_SPRINGS.find((item) => item.spring_id === id))} /><p className="map-caption">The DHAARA analysis canvas visualises documented discharge change only where paired observations exist.</p></section>
    <section id="analysis" className="content-section evidence-section"><div><p className="panel-label">DOCUMENTED HYDROGEOLOGY</p><h2>{spring.name}</h2><p>{spring.region}</p></div><div className="evidence-list">{[['Elevation', displayValue(spring.elevation, ' m')], ['Spring type', text(spring.type)], ['Geology / aquifer', text(spring.geology)], ['Recharge interpretation', text(spring.rechargeDescription)], ['Source', spring.source], ['Data quality', spring.dataQuality]].map(([name, value]) => <div key={name}><b>{name}</b><span>{value}</span></div>)}</div></section>
    <section id="interventions" className="content-section assessment-section"><div><p className="panel-label">DOCUMENTED CHANGE</p><h2>Observed water levels, not invented recommendations.</h2><p>{paired ? `The source records discharge changing from ${spring.discharge2010} L/min in 2010 to ${spring.discharge2011} L/min in 2011.` : 'The supplied source does not establish a paired 2010–2011 discharge series for this record.'}</p></div><div className="assessment-results"><span><b>{paired ? spring.discharge2010 : '—'}<small>{paired ? ' L/min' : ''}</small></b>2010 documented discharge</span><span><b>{paired ? spring.discharge2011 : '—'}<small>{paired ? ' L/min' : ''}</small></b>2011 documented discharge</span></div></section>
    <section id="fieldwork" className="content-section field-section"><div><p className="panel-label">FIELDWORK</p><h2>What should be verified on site?</h2><p>Confirm source location, discharge, water quality, spring condition, recharge-side observations, and local land-use context before acting on this record.</p></div><button className="dark-button" onClick={() => window.print()}>Prepare field sheet →</button></section>
    <section id="reports" className="report-section"><div><p className="panel-label">REPORT</p><h2>Share the documented record.</h2><p>Print the selected spring profile, its source quality, hydrogeology, and documented water observations.</p></div><button className="dark-button" onClick={() => window.print()}>Generate report →</button></section>
  </div></main></div>;
}
