import React, { useEffect, useRef, useState } from 'react';
import { Map, NavigationControl, Popup, setWorkerUrl } from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import { hasPairedDischarge } from '../../data/demoAnalysis';

const readable = (value, suffix = '') => value === null || value === undefined ? 'Not established' : `${value}${suffix}`;
const STYLE = 'https://tiles.openfreemap.org/styles/liberty';
const FALLBACK = [88.38, 27.12];
const located = (spring) => Number.isFinite(spring?.latitude) && Number.isFinite(spring?.longitude);
const point = (spring) => located(spring) ? [spring.longitude, spring.latitude] : FALLBACK;
setWorkerUrl(workerUrl);

function DhaaraAnalysisMap({ spring }) {
  const paired = hasPairedDischarge(spring);
  const max = paired ? Math.max(spring.discharge2010, spring.discharge2011) : 1;
  const firstHeight = paired ? Math.max(28, (spring.discharge2010 / max) * 158) : 0;
  const secondHeight = paired ? Math.max(28, (spring.discharge2011 / max) * 158) : 0;
  return <div className="dhaara-analysis-map"><div className="dhaara-map-bar"><b>DHAARA / ANALYSIS MAP</b><span>{spring.name}</span><i>●</i></div><div className="dhaara-map-stage"><svg viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"><defs><pattern id="dhaara-grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="currentColor" strokeWidth="1" /></pattern></defs><rect width="1000" height="520" fill="url(#dhaara-grid)" className="dhaara-grid" /><path d="M-30 75 C145 25 245 155 390 105 S630 35 790 126 S930 180 1050 76 M-30 175 C130 110 255 235 405 178 S650 120 810 205 S950 250 1060 142 M-30 275 C135 190 255 330 408 275 S655 205 815 300 S950 345 1060 240 M-30 375 C125 295 270 430 432 358 S670 295 820 400 S940 455 1060 345" className="dhaara-contour" /><path d="M40 430 C245 370 360 500 548 408 S818 342 1000 440" className="dhaara-water" />{spring.type?.toLowerCase().includes('fracture') && <path d="M220 30 L448 468 M600 30 L746 492" className="dhaara-fracture" />}</svg><div className="dhaara-spring-node"><span /><b>{spring.name}</b><small>{spring.type || 'Type not established'}</small></div>{paired ? <div className="discharge-bars"><p>DOCUMENTED DISCHARGE · L/MIN</p><div className="bar-row"><div><i style={{ height: `${firstHeight}px` }} /><b>{spring.discharge2010}</b><span>2010</span></div><div><i className="current" style={{ height: `${secondHeight}px` }} /><b>{spring.discharge2011}</b><span>2011</span></div></div><strong>{(spring.discharge2011 / spring.discharge2010).toFixed(1)}× observed change</strong></div> : <div className="no-discharge"><b>NO PAIRED DISCHARGE SERIES</b><span>{Number.isFinite(spring.discharge2011) ? `${spring.discharge2011} L/min documented in 2011` : 'The supplied source does not establish paired discharge values.'}</span></div>}<div className="dhaara-map-key"><span><i className="spring-dot" /> Documented spring</span><span><i className="water-line" /> Drainage context</span>{spring.type?.toLowerCase().includes('fracture') && <span><i className="fracture-line" /> Fracture spring</span>}</div></div><div className="dhaara-data-strip"><span><b>Elevation</b>{readable(spring.elevation, ' m')}</span><span><b>Geology</b>{spring.geology || 'Not established'}</span><span><b>Source quality</b>{spring.dataQuality}</span></div></div>;
}

function TerrainMap({ spring, springs, onSelectSpring }) {
  const target = useRef(null); const mapRef = useRef(null); const [status, setStatus] = useState('Loading terrain map…');
  useEffect(() => { if (!target.current) return undefined; const map = new Map({ container: target.current, style: STYLE, center: point(spring), zoom: located(spring) ? 12 : 10, attributionControl: true }); mapRef.current = map; map.addControl(new NavigationControl({ showCompass: false }), 'bottom-right'); map.once('load', () => { const features = springs.filter(located).map((item) => ({ type: 'Feature', properties: { id: item.spring_id, name: item.name, type: item.type || 'Type not established' }, geometry: { type: 'Point', coordinates: point(item) } })); map.addSource('documented-springs', { type: 'geojson', data: { type: 'FeatureCollection', features } }); map.addSource('selected-spring', { type: 'geojson', data: { type: 'FeatureCollection', features: [] } }); map.addLayer({ id: 'documented-springs', type: 'circle', source: 'documented-springs', paint: { 'circle-radius': 7, 'circle-color': '#d9ecae', 'circle-stroke-width': 2, 'circle-stroke-color': '#153b2a' } }); map.addLayer({ id: 'selected-spring-halo', type: 'circle', source: 'selected-spring', paint: { 'circle-radius': 23, 'circle-color': '#d9f19a', 'circle-opacity': .35, 'circle-blur': .3 } }); map.addLayer({ id: 'selected-spring', type: 'circle', source: 'selected-spring', paint: { 'circle-radius': 11, 'circle-color': '#183c2b', 'circle-stroke-width': 4, 'circle-stroke-color': '#f8f7ed' } }); map.on('click', 'documented-springs', (event) => { const feature = event.features?.[0]; if (!feature) return; onSelectSpring?.(feature.properties.id); }); map.on('mouseenter', 'documented-springs', () => { map.getCanvas().style.cursor = 'pointer'; }); map.on('mouseleave', 'documented-springs', () => { map.getCanvas().style.cursor = ''; }); setStatus(''); }); map.on('error', () => setStatus('Terrain map could not load. Please retry.')); return () => map.remove(); }, []);
  useEffect(() => { const map = mapRef.current; if (!map?.isStyleLoaded()) return; const data = { type: 'FeatureCollection', features: located(spring) ? [{ type: 'Feature', properties: { name: spring.name }, geometry: { type: 'Point', coordinates: point(spring) } }] : [] }; map.getSource('selected-spring')?.setData(data); if (located(spring)) map.flyTo({ center: point(spring), zoom: 13, essential: true }); }, [spring]);
  return <div className="real-terrain-map"><div ref={target} className="real-terrain-canvas" />{status && <span className="terrain-status">{status}</span>}<div className="terrain-topline"><b>REAL TERRAIN MAP</b><span>{springs.filter(located).length} documented coordinates</span></div>{!located(spring) && <div className="terrain-note">No coordinate was supplied for <b>{spring.name}</b>. The map remains centred on the documented South Sikkim records.</div>}<div className="terrain-legend"><i /> Documented coordinate</div></div>;
}

export function GeoMap({ spring, springs, onSelectSpring }) {
  const [mode, setMode] = useState('analysis');
  return <div className="geo-map-shell atlas-map">{mode === 'analysis' ? <DhaaraAnalysisMap spring={spring} /> : <TerrainMap spring={spring} springs={springs} onSelectSpring={onSelectSpring} />}<div className="map-mode-switch"><button className={mode === 'analysis' ? 'active' : ''} onClick={() => setMode('analysis')}>DHAARA analysis</button><button className={mode === 'terrain' ? 'active' : ''} onClick={() => setMode('terrain')}>Real terrain</button></div></div>;
}
