import React, { useState } from 'react';
import { hasPairedDischarge } from '../../data/demoAnalysis';

const readable = (value, suffix = '') => value === null || value === undefined ? 'Not established' : `${value}${suffix}`;

function DhaaraAnalysisMap({ spring }) {
  const paired = hasPairedDischarge(spring);
  const max = paired ? Math.max(spring.discharge2010, spring.discharge2011) : 1;
  const firstHeight = paired ? Math.max(28, (spring.discharge2010 / max) * 158) : 0;
  const secondHeight = paired ? Math.max(28, (spring.discharge2011 / max) * 158) : 0;
  return <div className="dhaara-analysis-map"><div className="dhaara-map-bar"><b>DHAARA / ANALYSIS MAP</b><span>{spring.name}</span><i>●</i></div><div className="dhaara-map-stage"><svg viewBox="0 0 1000 520" preserveAspectRatio="none" aria-hidden="true"><defs><pattern id="dhaara-grid" width="48" height="48" patternUnits="userSpaceOnUse"><path d="M 48 0 L 0 0 0 48" fill="none" stroke="currentColor" strokeWidth="1" /></pattern></defs><rect width="1000" height="520" fill="url(#dhaara-grid)" className="dhaara-grid" /><path d="M-30 75 C145 25 245 155 390 105 S630 35 790 126 S930 180 1050 76 M-30 175 C130 110 255 235 405 178 S650 120 810 205 S950 250 1060 142 M-30 275 C135 190 255 330 408 275 S655 205 815 300 S950 345 1060 240 M-30 375 C125 295 270 430 432 358 S670 295 820 400 S940 455 1060 345" className="dhaara-contour" /><path d="M40 430 C245 370 360 500 548 408 S818 342 1000 440" className="dhaara-water" />{spring.type?.toLowerCase().includes('fracture') && <path d="M220 30 L448 468 M600 30 L746 492" className="dhaara-fracture" />}</svg><div className="dhaara-spring-node"><span /><b>{spring.name}</b><small>{spring.type || 'Type not established'}</small></div>{paired ? <div className="discharge-bars"><p>DOCUMENTED DISCHARGE · L/MIN</p><div className="bar-row"><div><i style={{ height: `${firstHeight}px` }} /><b>{spring.discharge2010}</b><span>2010</span></div><div><i className="current" style={{ height: `${secondHeight}px` }} /><b>{spring.discharge2011}</b><span>2011</span></div></div><strong>{(spring.discharge2011 / spring.discharge2010).toFixed(1)}× observed change</strong></div> : <div className="no-discharge"><b>NO PAIRED DISCHARGE SERIES</b><span>{Number.isFinite(spring.discharge2011) ? `${spring.discharge2011} L/min documented in 2011` : 'The supplied source does not establish paired discharge values.'}</span></div>}<div className="dhaara-map-key"><span><i className="spring-dot" /> Documented spring</span><span><i className="water-line" /> Drainage context</span>{spring.type?.toLowerCase().includes('fracture') && <span><i className="fracture-line" /> Fracture spring</span>}</div></div><div className="dhaara-data-strip"><span><b>Elevation</b>{readable(spring.elevation, ' m')}</span><span><b>Geology</b>{spring.geology || 'Not established'}</span><span><b>Source quality</b>{spring.dataQuality}</span></div></div>;
}

export function GeoMap({ spring, springs, onSelectSpring }) {
  const [mode, setMode] = useState('analysis');
  return <div className="geo-map-shell atlas-map">{mode === 'analysis' ? <DhaaraAnalysisMap spring={spring} /> : <div className="terrain-record-map"><p>DOCUMENTED COORDINATE INVENTORY</p><h3>{spring.name}</h3><span>{Number.isFinite(spring.latitude) ? `${spring.latitude.toFixed(5)}° N · ${spring.longitude.toFixed(5)}° E` : 'Coordinates are not established in the supplied source for this record.'}</span><div>{springs.map((item) => <button key={item.spring_id} className={item.spring_id === spring.spring_id ? 'selected' : ''} onClick={() => onSelectSpring?.(item.spring_id)}>{item.name}<small>{Number.isFinite(item.latitude) ? 'Mapped coordinate' : 'No coordinate supplied'}</small></button>)}</div></div>}<div className="map-mode-switch"><button className={mode === 'analysis' ? 'active' : ''} onClick={() => setMode('analysis')}>DHAARA analysis</button><button className={mode === 'terrain' ? 'active' : ''} onClick={() => setMode('terrain')}>Source records</button></div></div>;
}
