import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Map, NavigationControl, Popup, setWorkerUrl } from 'maplibre-gl';
import workerUrl from 'maplibre-gl/dist/maplibre-gl-worker.mjs?worker&url';
import 'maplibre-gl/dist/maplibre-gl.css';
import { spatialDataFor } from '../../data/demoAnalysis';

setWorkerUrl(workerUrl);
const STYLE = 'https://tiles.openfreemap.org/styles/liberty';
const FALLBACK = [88.23105, 27.189017];
const located = (s) => Number.isFinite(s?.longitude) && Number.isFinite(s?.latitude);
const point = (s) => located(s) ? [s.longitude, s.latitude] : FALLBACK;
const inventory = (springs) => ({ type: 'FeatureCollection', features: springs.filter(located).map((s) => ({ type: 'Feature', properties: { id: s.spring_id, name: s.name, region: s.region, elevation: s.elevation, type: s.type, historical: Boolean(s.discharge2010) }, geometry: { type: 'Point', coordinates: point(s) } })) });
const drainage = (s) => { const [x, y] = point(s); return { type: 'FeatureCollection', features: [{ type: 'Feature', geometry: { type: 'LineString', coordinates: [[x - .04, y + .025], [x - .015, y + .008], [x + .012, y - .01], [x + .045, y - .034]] }, properties: { source: 'Demonstration drainage context' } }] }; };

export function GeoMap({ spring, springs, analysed, showSites, onSelectSite, onSelectSpring }) {
  const target = useRef(null); const mapRef = useRef(null); const [state, setState] = useState('loading'); const [error, setError] = useState(''); const [retry, setRetry] = useState(0); const [open, setOpen] = useState(false); const [layers, setLayers] = useState({ springs: true, drainage: true, recharge: true, risk: false });
  const update = useCallback(() => { const map = mapRef.current; if (!map?.isStyleLoaded()) return; const data = spatialDataFor(spring); map.getSource('inventory')?.setData(inventory(springs)); map.getSource('drainage')?.setData(drainage(spring)); map.getSource('recharge')?.setData(data.recharge); map.getSource('sites')?.setData(data.sites); const show = (id, value) => map.getLayer(id) && map.setLayoutProperty(id, 'visibility', value ? 'visible' : 'none'); show('inventory', layers.springs); show('drainage', layers.drainage); show('recharge-fill', analysed && layers.recharge); show('recharge-line', analysed && layers.recharge); show('sites', analysed && showSites); show('site-risk', analysed && showSites && layers.risk); }, [spring, springs, analysed, showSites, layers]);
  useEffect(() => { if (!target.current) return undefined; const map = new Map({ container: target.current, style: STYLE, center: point(spring), zoom: 12.1, attributionControl: true }); mapRef.current = map; map.addControl(new NavigationControl({ showCompass: false }), 'bottom-right'); const timer = window.setTimeout(() => { if (!map.isStyleLoaded()) { setState('error'); setError('The basemap did not respond. Check your connection and retry.'); } }, 8000); map.on('error', (e) => e?.error?.message && console.error('[DHAARA MapLibre]', e.error));
    map.once('load', () => { window.clearTimeout(timer); const d = spatialDataFor(spring); [['inventory', inventory(springs)], ['drainage', drainage(spring)], ['recharge', d.recharge], ['sites', d.sites]].forEach(([id, data]) => map.addSource(id, { type: 'geojson', data })); map.addLayer({ id: 'drainage', type: 'line', source: 'drainage', paint: { 'line-color': '#4a8795', 'line-width': 2.2, 'line-opacity': .72 } }); map.addLayer({ id: 'recharge-fill', type: 'fill', source: 'recharge', layout: { visibility: 'none' }, paint: { 'fill-color': ['match', ['get', 'class'], 'High', '#7f9e5b', '#c4a565'], 'fill-opacity': .28 } }); map.addLayer({ id: 'recharge-line', type: 'line', source: 'recharge', layout: { visibility: 'none' }, paint: { 'line-color': '#46613d', 'line-width': 1.2 } }); map.addLayer({ id: 'inventory', type: 'circle', source: 'inventory', paint: { 'circle-radius': ['case', ['==', ['get', 'id'], spring.spring_id], 8, 5], 'circle-color': ['case', ['get', 'historical'], '#5b7d4e', '#eef1e6'], 'circle-stroke-color': '#19372a', 'circle-stroke-width': 1.5 } }); map.addLayer({ id: 'sites', type: 'circle', source: 'sites', layout: { visibility: 'none' }, paint: { 'circle-radius': 7, 'circle-color': ['match', ['get', 'risk'], 'Low', '#78934f', 'Moderate', '#b18a4d', '#9d6559'], 'circle-stroke-width': 1.5, 'circle-stroke-color': '#fff' } }); map.addLayer({ id: 'site-risk', type: 'circle', source: 'sites', layout: { visibility: 'none' }, paint: { 'circle-radius': 13, 'circle-color': '#a06a61', 'circle-opacity': .16 } });
      map.on('click', 'inventory', (e) => { const f = e.features?.[0]; if (!f) return; const p = f.properties; const root = document.createElement('div'); root.className = 'map-popup'; root.innerHTML = `<strong>${p.name}</strong><span>${p.region}</span><dl><div><dt>Elevation</dt><dd>${p.elevation} m</dd></div><div><dt>Spring type</dt><dd>${p.type}</dd></div></dl>`; const button = document.createElement('button'); button.textContent = 'View spring'; button.onclick = () => onSelectSpring?.(p.id); root.append(button); new Popup({ closeButton: false, offset: 12 }).setLngLat(f.geometry.coordinates).setDOMContent(root).addTo(map); }); map.on('click', 'sites', (e) => e.features?.[0] && onSelectSite?.(e.features[0].properties.id)); map.on('mouseenter', 'inventory', () => { map.getCanvas().style.cursor = 'pointer'; }); map.on('mouseleave', 'inventory', () => { map.getCanvas().style.cursor = ''; }); setState('ready'); });
    return () => { window.clearTimeout(timer); map.remove(); mapRef.current = null; }; }, [retry]);
  useEffect(() => update(), [update]); useEffect(() => { if (mapRef.current && located(spring)) mapRef.current.flyTo({ center: point(spring), zoom: 12.1, essential: true }); }, [spring]); const toggle = (key) => setLayers((x) => ({ ...x, [key]: !x[key] }));
  return <div className="geo-map-shell atlas-map"><div ref={target} className="geo-map" />{state === 'loading' && <div className="map-status">Loading geographic context…</div>}{state === 'error' && <div className="map-error"><b>Map data unavailable</b><span>{error}</span><button onClick={() => { setState('loading'); setError(''); setRetry((x) => x + 1); }}>Retry map</button></div>}<div className="map-topline"><span>SIKKIM SPRING INVENTORY</span><span>{springs.filter(located).length} mapped records</span></div><div className="map-tools"><button onClick={() => setOpen((x) => !x)}>Layers</button><button onClick={() => mapRef.current?.flyTo({ center: point(spring), zoom: 12.1 })}>Locate</button></div>{open && <div className="layer-menu"><b>Map layers</b>{[['springs','Springs'],['drainage','Drainage'],['recharge','Recharge suitability'],['risk','Risk screening']].map(([key, label]) => <label key={key}><input type="checkbox" checked={layers[key]} onChange={() => toggle(key)} />{label}</label>)}<small>Elevation, land cover, rainfall and geology are currently evidence records, not live map services.</small></div>}<div className="map-legend"><p>SPRING STATUS</p><span><i className="inventory-dot" /> Inventoried</span><span><i className="verified-dot" /> Historical intervention record</span></div></div>;
}
